### ISSUE TITLE
🐞 - emitEvent config for control does not work

### ISSUE THREAD

**Issue by Ultraviolence322** [taiga-family/tui-editor#101]
### Playground Link

https://stackblitz.com/edit/angular-5sxteh?file=src%2Fapp%2Fapp.component.ts&hideExplorer=1

### Description

![image](https://github.com/taiga-family/tui-editor/assets/53703949/6e317fd1-1799-4076-ad66-0a3293b23d03)

### Angular version

12.2.17

### Taiga UI version

1.2.0

### Which browsers have you used?

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [X] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by splincode** [comment]
@waterplea Hello, I understand correctly that there is no bug here, because this is how reactive forms work?
