### ISSUE TITLE
🚀 - ` @tiptap/extension-*` and most `prosemirror-*` dependencies should be marked as `optional`

### ISSUE THREAD

**Issue by hakimio** [taiga-family/tui-editor#1092]
### Description

In the new `@tbank/tui-editor` alpha version I can see that most dependencies were moved to [peer dependencies](https://github.com/taiga-family/tui-editor/blob/473ff1a93780c525ebec7ea1061a047fbe18dc09/projects/editor/package.json#L16).
The problem with peer dependencies is that they are still required even you can control their version to some extent.
However, in this case most of the extensions are optional and, if you provide your own default extension list, you don't need them.

I would suggest to use [peerDependenciesMeta](https://docs.npmjs.com/cli/v10/configuring-npm/package-json#peerdependenciesmeta) to mark at least some of the peer dependencies as `optional`.

**Comment by splincode** [comment]
@hakimio Welcome to contribute
