### ISSUE TITLE
🐞 - If copy some links and paste into editor text field all of links will contain the same URL

### ISSUE THREAD

**Issue by dkuptsova** [taiga-family/tui-editor#577]
### Playground Link

https://taiga-family.github.io/tui-editor/starter-kit

### Description

1. Copy some links from the document (in my case it was wiki)
2. Paste them into editor text field
3. Click on each one
<img width="1222" alt="Снимок экрана 2023-12-05 в 18 06 07" src="https://github.com/taiga-family/tui-editor/assets/152492774/4dc1c68e-2fca-4098-bb13-db84603a0984">

Result:
all of links contain the same URL (url of the first link in the list)

### Angular version

15.2.0

### Taiga UI version

3.38.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [X] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by splincode** [comment]
I can't reproduce

**Comment by dkuptsova** [comment]
Hi. Maybe I explained it wrong. If copy some links and paste them simultaneously problem is reproducing. I checked here  https://taiga-family.github.io/tui-editor/starter-kit 

https://github.com/taiga-family/tui-editor/assets/152492774/4455bf2d-becc-4bc7-86ab-8b4f2958c6b3

**Comment by splincode** [comment]
Could you add video example with reproduction on https://taiga-family.github.io/editor/starter-kit?
