### ISSUE TITLE
🐞 - Editing links in the Editor component doesn't work for Safari 17.1 (18616.2.9.11.9, 18616) 

### ISSUE THREAD

**Issue by dkuptsova** [taiga-family/tui-editor#580]
### Playground Link

https://taiga-family.github.io/tui-editor/starter-kit

### Description

Description
Preconditions:
Insert two links into Editor

Problem 1

Click on first link - menu with edit/remove buttons appears
Click "Edit"
Set cursor into the link field
Move cursor to the end of link
Result:
I cannot see the end of link
Problem 2 and 3

Click on first link - menu with edit/remove buttons appears
Click "Edit"
Change the link
Click "Apply"
Click "Edit"
Result:
The link didn't changed
Then
Click on the second link
Click "Edit"
Result:
menu with edit/remove buttons doesn't appear
WA: If make some changes into the Editor - add the line, then menu buttons appear if click on the link
Also editing and removing links in the Editor doesn't work for Safari 16.6 (18615.3.12.11.2)

https://github.com/taiga-family/tui-editor/assets/152492774/65244e17-7ec8-4ab9-851a-505c6e327377

In Chrome it's OK
Discussion: https://time.tinkoff.ru/tinkoff/pl/kn9j41nqptfgzy5bj3inr94tkh

### Angular version

15.2.0

### Taiga UI version

3.38.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [X] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by dkuptsova** [comment]
Hi. I've checked this fix here https://taiga-ui.tcsbank.ru/components/editor
The problem is still being reproduced.
Safari Версия 17.1 (18616.2.9.11.9, 18616)

https://github.com/taiga-family/tui-editor/assets/152492774/37d737f3-b6f1-4f7b-9b1b-2abe7aec7b32

**Comment by splincode** [comment]
https://github.com/taiga-family/tui-editor/assets/12021443/8ada4436-bfed-46ae-8130-090c39ccd709

**Comment by dkuptsova** [comment]
Yes. It's OK for version 17.0. But this is reproducible in version 17.1

**Comment by splincode** [comment]
fixed
