### ISSUE TITLE
🚀 - Show Editor-Toolbar when only custom tools are available

### ISSUE THREAD

**Issue by michael-hein** [taiga-family/tui-editor#997]
### Description

Currently when not at least one build in tool is selected, then the toolbar is hidden.
For the rare case when there is only a few custom tools available and no buildin tools, then the tool bar is hidden.

So is there a possiblity to make the toolbar visible?

https://github.com/taiga-family/tui-editor/blob/9ffe745f17063c7fd153d8e17a3ad356686b646a/projects/editor/src/components/editor/editor.component.html#L14-L16

Workaround would be to provide a buildin tool and hide it via styles.

Thank you :)

**Comment by splincode** [comment]
@michael-hein If you pass an empty array of tools, what's the point?

<img width="1168" alt="image" src="https://github.com/taiga-family/tui-editor/assets/12021443/6179d2df-ae6f-4d7e-9d74-348d40aa8ccb">

**Comment by michael-hein** [comment]
@splincode then `tools.length` is false or not?

https://stackblitz.com/edit/angular-um3yes?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts&hideExplorer=1

with tools
![image](https://github.com/taiga-family/tui-editor/assets/51996054/e8eaa10c-a631-4bec-9e18-ba147bc6f681)

with empty tool array
![image](https://github.com/taiga-family/tui-editor/assets/51996054/e8193a79-2516-47fc-bcd3-5366440f0411)

**Comment by splincode** [comment]
fixed by v1.26
